language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
install:
   - "if [[ $DJANGO_VERSION == 'dev' ]]; then pip install https://github.com/django/django/archive/master.tar.gz#egg=Django; else pip install Django==$DJANGO_VERSION --use-mirrors; fi"
   - pip install git+https://github.com/ella/ella.git#egg=ella
   - pip install -r dev_requirements.txt --use-mirrors
   - python setup.py develop
env:
  - DJANGO_VERSION=1.3.3
  - DJANGO_VERSION=1.4.1
  - DJANGO_VERSION=dev
script: python setup.py test
matrix:
    exclude:
       - python: "2.5"
         env: DJANGO_VERSION=dev
